// Stage 1 (C.3): migrate the Babel-in-browser prototype to a single Vite/esbuild ES
// module. We concatenate the prototype scripts (same order as the old HTML) into one
// module scope — which is exactly the shared scope Babel's global eval gave them, so
// the window-global pattern and bare cross-file references keep working — and prepend
// real React/ReactDOM imports + an asset resolver. JSX is transpiled at build time.
import { readFileSync, writeFileSync } from 'node:fs';

const PROJ = 'project';
// Same load order as project/AutoSpec Studio.html
const FILES = [
  'icons.jsx', 'data.jsx',
  'import_3008.js', 'import_c3.js', 'import_library.js', 'import_meta.js',
  'ui.jsx', 'catalogrender.jsx',
  'screen_dashboard.jsx', 'screen_templates.jsx', 'screen_newcatalog.jsx',
  'screen_learn_data.jsx', 'screen_learn_review.jsx', 'screen_learn_panels.jsx',
  'screen_learn_compare.jsx', 'screen_learn.jsx',
  'screen_editor_panels.jsx', 'screen_editor.jsx', 'screen_export.jsx',
  'tweaks-panel.jsx', 'app.jsx',
];

const header = `/* AUTO-GENERATED by scripts/build-legacy.mjs — do not edit by hand.
   Source: project/*.jsx + project/import_*.js (the design prototype UI).
   This is the Stage-1 build migration: same code, now a real ES module (no Babel-in-
   browser). Heavy data + assets are no longer inlined in HTML — images resolve to
   /public URLs via window.__res. The PDF engine rebuild happens in later stages. */
import React from 'react';
import { createRoot } from 'react-dom/client';
import './legacy.css';
import './legacy-extra.css';

// Provide the globals the prototype expects (it was written against UMD globals).
// Module-scope bindings so bare \`React\`/\`ReactDOM\` references resolve everywhere
// (a real browser exposes window.* as globals; bundlers/SSR do not).
const ReactDOM = { createRoot };
window.React = React;
window.ReactDOM = ReactDOM;
// Assets (previews, logos) are served from /public; data references bare paths.
window.__res = (p) => (typeof p === 'string' && p && !/^(https?:|data:|blob:|\\/)/.test(p) ? '/' + p : p);


`;

const parts = [header];
for (const f of FILES) {
  parts.push(`\n/* ===== ${f} ===== */\n`);
  parts.push(readFileSync(`${PROJ}/${f}`, 'utf8'));
}

writeFileSync('src/legacy/legacy-app.jsx', parts.join('\n'));
console.log(`wrote src/legacy/legacy-app.jsx from ${FILES.length} prototype files`);
